name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: PR CI (Test and Coverage)
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]
    name: test/node ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm config set timeout 600000
      - run: npm install
      - run: npm run build
      - run: npm test

  lint:
    runs-on: ubuntu-latest
    environment: PR CI (Test and Coverage)
    name: test/lint
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: wagoid/commitlint-github-action@v4
      - run: npm config set timeout 600000
      - run: npm install
      - run: npm run lint

  coverage:
    needs: [test]
    name: coverage
    runs-on: ubuntu-latest
    environment: PR CI (Test and Coverage)
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 16.x
    - run: npm config set timeout 600000
    - run: npm install
    - run: npm run build
    - uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: npm run coverage
        debug: true
